language: python
python:
  - 3.9
install:
  - pip install -q -r requirements-dev.txt codecov
script:
  - flake8
  - pytest libpythonprogoldani --cov=libpythonprogoldani
after_success:
  - codecov CODECOV_TOKEN='2f263c5c-71a7-4082-8df8-934eceaae287'